# Python script to generate 365+ authentic Prophetic reminders
import json

hadiths = []

def add(text, source, category):
    hadiths.append({
        "id": len(hadiths) + 1,
        "text": text.strip(),
        "source": source.strip(),
        "category": category.strip()
    })

# --- 1. RAMADAN, FASTING & SUHUR / IFTAR (1-35) ---
add("Whoever fasts the month of Ramadan out of sincere faith and hoping for reward, all his past sins will be forgiven.", "Sahih al-Bukhari 38", "Ramadan & Fasting")
add("When the month of Ramadan arrives, the gates of Paradise are opened, the gates of Hell are closed, and the devils are chained.", "Sahih al-Bukhari 1899", "Ramadan & Fasting")
add("Fasting is a shield; so when one of you is fasting, he should neither indulge in obscene language nor act foolishly. If someone fights or insults him, let him say: 'I am fasting.'", "Sahih al-Bukhari 1894", "Ramadan & Fasting")
add("Take Suhur (the pre-dawn meal), for indeed there is blessing in Suhur.", "Sahih al-Bukhari 1923", "Ramadan & Fasting")
add("The people will continue to prosper as long as they hasten the breaking of the fast (at sunset).", "Sahih al-Bukhari 1957", "Ramadan & Fasting")
add("Whoever provides food for a fasting person to break his fast will have a reward like his, without anything being lessened from the reward of the fasting person.", "Jami at-Tirmidhi 807", "Ramadan & Fasting")
add("There are two joys for the fasting person: when he breaks his fast he rejoices, and when he meets his Lord he rejoices over his fast.", "Sahih al-Bukhari 1904", "Ramadan & Fasting")
add("In Paradise there is a gate called Ar-Rayyan, through which only those who fast will enter on the Day of Resurrection.", "Sahih al-Bukhari 1896", "Ramadan & Fasting")
add("Whoever stands in prayer during the nights of Ramadan out of faith and seeking reward, his past sins will be forgiven.", "Sahih al-Bukhari 37", "Ramadan & Fasting")
add("Look for Laylatul Qadr (the Night of Decree) in the odd nights of the last ten days of Ramadan.", "Sahih al-Bukhari 2017", "Ramadan & Fasting")
add("Whoever stands in prayer on Laylatul Qadr out of faith and seeking reward, all his past sins will be forgiven.", "Sahih al-Bukhari 1901", "Ramadan & Fasting")
add("The Prophet was the most generous of people, and he was at his most generous in Ramadan when Jibril would meet with him.", "Sahih al-Bukhari 6", "Ramadan & Fasting")
add("Fasting and the Qur’an will intercede for the servant on the Day of Resurrection.", "Musnad Ahmad 6626", "Ramadan & Fasting")
add("Allah the Exalted says: Every deed of the son of Adam is for him, except fasting; it is for Me, and I shall reward for it.", "Sahih al-Bukhari 1904", "Ramadan & Fasting")
add("The smell coming from the mouth of a fasting person is more pleasant to Allah than the scent of musk.", "Sahih al-Bukhari 1894", "Ramadan & Fasting")
add("The supplication of three persons is not turned away: the fasting person when he breaks his fast, the just ruler, and the prayer of the oppressed.", "Jami at-Tirmidhi 3598", "Ramadan & Fasting")
add("Whoever does not give up false speech and evil action, Allah has no need of his leaving his food and drink.", "Sahih al-Bukhari 1903", "Ramadan & Fasting")
add("When breaking your fast, break it with fresh dates; if not available, then dried dates; if not available, then with water, for water is pure.", "Sunan Abi Dawud 2355", "Ramadan & Fasting")
add("The difference between our fasting and the fasting of the people of the Book is the eating of Suhur.", "Sahih Muslim 1096", "Ramadan & Fasting")
add("Whoever fasts Ramadan and then follows it with six days of Shawwal, it is as if he fasted for a lifetime.", "Sahih Muslim 1164", "Ramadan & Fasting")
add("The best prayer after the obligatory prayers is the night prayer, and the best fast after Ramadan is the month of Allah, Muharram.", "Sahih Muslim 1163", "Ramadan & Fasting")
add("Fasting three days of each month (the white days) is like fasting for an entire lifetime.", "Sahih al-Bukhari 1979", "Ramadan & Fasting")
add("Whoever forgets that he is fasting and eats or drinks, let him complete his fast, for it was Allah who fed him and gave him drink.", "Sahih al-Bukhari 1933", "Ramadan & Fasting")
add("O Allah, You are Pardoning and generous, and You love to pardon, so pardon me. (Du'a for Laylatul Qadr)", "Jami at-Tirmidhi 3513", "Ramadan & Fasting")
add("When the last ten nights of Ramadan arrived, the Prophet would tighten his waist belt, stay awake at night, and awaken his family.", "Sahih al-Bukhari 2024", "Ramadan & Fasting")
add("Fasting is prescribed for you as it was prescribed for those before you, that you may attain Taqwa (mindfulness of Allah).", "Surah al-Baqarah 2:183", "Ramadan & Fasting")
add("Eat Suhur, even if it is just a sip of water, for Allah and His angels send blessings upon those who take the pre-dawn meal.", "Sahih Ibn Hibban 3476", "Ramadan & Fasting")
add("The thirst has gone, the veins are moistened, and the reward is confirmed, if Allah wills. (Dua upon breaking fast)", "Sunan Abi Dawud 2357", "Ramadan & Fasting")
add("A fasting person's supplication at the moment of Iftar is never rejected.", "Sunan Ibn Majah 1753", "Ramadan & Fasting")
add("Whoever observes the fast with complete faith and accountability will have their heart purified of rancor.", "Sunan an-Nasa'i 2384", "Ramadan & Fasting")
add("Charity given during Ramadan is the most virtuous of charity.", "Jami at-Tirmidhi 663", "Ramadan & Fasting")
add("Recite the Qur’an frequently in Ramadan, for it will come as an intercessor for its companions on the Day of Judgment.", "Sahih Muslim 804", "Ramadan & Fasting")
add("He who observed the fast of Ramadan and knew its limits, and guarded against what ought to be avoided, expiates all his previous sins.", "Bayhaqi 3426", "Ramadan & Fasting")
add("May his nose be rubbed in dust, the one upon whom Ramadan enters and passes before he is forgiven.", "Jami at-Tirmidhi 3545", "Ramadan & Fasting")
add("Do not fast a day or two before Ramadan begins, unless it is a day a person usually fasts.", "Sahih al-Bukhari 1914", "Ramadan & Fasting")

# --- 2. SALAH, TAHAJJUD & MOSQUES (36-70) ---
add("The first matter that the slave will be brought to account for on the Day of Judgment is the prayer.", "Sunan an-Nasa'i 465", "Prayer & Salah")
add("Between a person and disbelief or polytheism is the abandonment of prayer.", "Sahih Muslim 82", "Prayer & Salah")
add("The five daily prayers and Friday to Friday are an expiation for whatever sins occur between them, provided major sins are avoided.", "Sahih Muslim 233", "Prayer & Salah")
add("Whoever prays the two cool prayers (Fajr and Asr) will enter Paradise.", "Sahih al-Bukhari 574", "Prayer & Salah")
add("Whoever performs the ablution (Wudu) well, his sins will come out from his body, even from beneath his fingernails.", "Sahih Muslim 245", "Prayer & Salah")
add("The closest a servant comes to his Lord is when he is prostrating (in Sujud), so make abundant supplication then.", "Sahih Muslim 482", "Prayer & Salah")
add("The prayer in congregation is twenty-seven times more virtuous than the prayer of a person alone.", "Sahih al-Bukhari 645", "Prayer & Salah")
add("Whoever attends Isha prayer in congregation, it is as if he stood in prayer for half the night; and whoever prays Fajr in congregation, it is as if he prayed the whole night.", "Sahih Muslim 656", "Prayer & Salah")
add("Give glad tidings to those who walk to the mosques in the dark of complete light on the Day of Resurrection.", "Sunan Abi Dawud 561", "Prayer & Salah")
add("Whoever builds a mosque for the sake of Allah, Allah will build for him a house like it in Paradise.", "Sahih al-Bukhari 450", "Prayer & Salah")
add("The two Sunnah rak'ahs before Fajr are better than the entire world and everything in it.", "Sahih Muslim 725", "Prayer & Salah")
add("Whoever regularly prays twelve rak'ahs of voluntary prayers during the day and night, a house will be built for him in Paradise.", "Sahih Muslim 728", "Prayer & Salah")
add("Our Lord descends every night to the lowest heaven when the last third of the night remains, saying: Who calls upon Me that I may answer him?", "Sahih al-Bukhari 1145", "Prayer & Salah")
add("Hold fast to the night prayer (Tahajjud), for it was the practice of the righteous before you and brings you closer to your Lord.", "Jami at-Tirmidhi 3549", "Prayer & Salah")
add("Make your prayers solemn and peaceful, and remember your Lord with deep tranquility in bowing and prostrating.", "Sahih al-Bukhari 757", "Prayer & Salah")
add("When any one of you stands to pray, he is in intimate conversation with his Lord.", "Sahih al-Bukhari 405", "Prayer & Salah")
add("Make the last of your prayers at night the Witr prayer.", "Sahih al-Bukhari 998", "Prayer & Salah")
add("The best of your days is Friday; on it Adam was created and on it he passed away. So send abundant blessings upon me on Friday.", "Sunan Abi Dawud 1047", "Prayer & Salah")
add("Whoever reads Surah al-Kahf on Friday will have a light that shines from him from one Friday to the next.", "Sunan al-Kubra 5856", "Prayer & Salah")
add("On Friday there is an hour in which no Muslim servant asks Allah for something good except that He gives it to him.", "Sahih al-Bukhari 935", "Prayer & Salah")
add("Cleanliness is half of faith, and Alhamdulillah fills the scale.", "Sahih Muslim 223", "Prayer & Salah")
add("When the call to prayer (Adhan) is made, supplicate, for supplications between the Adhan and Iqamah are not rejected.", "Sunan Abi Dawud 521", "Prayer & Salah")
add("Establish prayer at the beginning of its time, for that is among the deeds most beloved to Allah.", "Sahih al-Bukhari 527", "Prayer & Salah")
add("Prostration is the peak of submission: when a person prostrates, Satan weeps and says: 'The son of Adam was commanded to prostrate and he prostrated, so Paradise is his.'", "Sahih Muslim 81", "Prayer & Salah")
add("Whoever performs ablution and then says: 'Ashhadu alla ilaha illallah wahdahu la sharika lah...', the eight gates of Paradise will be opened for him.", "Sahih Muslim 234", "Prayer & Salah")
add("The coolness of my eyes was placed in prayer.", "Sunan an-Nasa'i 3940", "Prayer & Salah")
add("Do not leave off the Witr prayer, for Allah is One and He loves the odd number.", "Sunan Abi Dawud 1416", "Prayer & Salah")
add("Whoever walks to an obligatory prayer in congregation, it is like performing Hajj in the state of Ihram.", "Sunan Abi Dawud 558", "Prayer & Salah")
add("The angels send blessings upon any of you as long as he remains in his prayer space where he prayed, saying: 'O Allah, forgive him; O Allah, have mercy upon him.'", "Sahih al-Bukhari 445", "Prayer & Salah")
add("Straighten your rows in prayer, for straightening the rows is part of the perfection of prayer.", "Sahih al-Bukhari 723", "Prayer & Salah")
add("If people knew what reward there is in the call to prayer and the first row, and found no way except by drawing lots, they would draw lots.", "Sahih al-Bukhari 615", "Prayer & Salah")
add("Whoever guards his five daily prayers with their purification, bowings, and prostrations, they will be a light, proof, and salvation on the Day of Resurrection.", "Musnad Ahmad 6576", "Prayer & Salah")
add("No prayer is heavier upon the hypocrites than the Fajr and Isha prayers; had they known what is in them, they would have come even if crawling.", "Sahih al-Bukhari 657", "Prayer & Salah")
add("Shall I not inform you of something by which Allah wipes away sins and raises ranks? Performing Wudu thoroughly in hardship, taking many steps to the mosques, and waiting for the next prayer.", "Sahih Muslim 251", "Prayer & Salah")
add("When you stand to pray, pray as if it were your farewell prayer.", "Sunan Ibn Majah 4171", "Prayer & Salah")

# --- 3. DHIKR, DUA & REMEMBRANCE (71-110) ---
add("Two words are light on the tongue, heavy on the scales, and beloved to the Most Merciful: SubhanAllahi wa bihamdihi, SubhanAllahil-Azim.", "Sahih al-Bukhari 6682", "Dhikr & Remembrance")
add("The comparison between the one who remembers his Lord and the one who does not is like the comparison between the living and the dead.", "Sahih al-Bukhari 6407", "Dhikr & Remembrance")
add("Allah the Exalted says: I am with My servant when he remembers Me and his lips move with My remembrance.", "Sahih al-Bukhari 7405", "Dhikr & Remembrance")
add("Whoever says 'SubhanAllah wa bihamdihi' one hundred times a day, his sins will be forgiven even if they were like the foam of the sea.", "Sahih al-Bukhari 6405", "Dhikr & Remembrance")
add("The best remembrance is 'La ilaha illallah' (There is no god but Allah), and the best supplication is 'Alhamdulillah' (All praise belongs to Allah).", "Jami at-Tirmidhi 3383", "Dhikr & Remembrance")
add("Shall I not tell you of the best of your deeds and the purest in the sight of your Lord? It is the remembrance of Allah.", "Jami at-Tirmidhi 3377", "Dhikr & Remembrance")
add("Keep your tongue moist with the remembrance of Allah.", "Jami at-Tirmidhi 3375", "Dhikr & Remembrance")
add("Say: 'La hawla wa la quwwata illa billah' (There is no power nor might except with Allah), for it is a treasure from the treasures of Paradise.", "Sahih al-Bukhari 6384", "Dhikr & Remembrance")
add("Whoever says upon morning and evening: 'Radheetu billahi Rabba, wa bil-Islami deena, wa bi-Muhammadin Nabiyya', it will be a duty upon Allah to please him on the Day of Resurrection.", "Sunan Abi Dawud 5072", "Dhikr & Remembrance")
add("The supplication (Du'a) is the very essence of worship.", "Jami at-Tirmidhi 3371", "Dhikr & Remembrance")
add("Ask Allah with certainty that you will be answered, and know that Allah does not answer a supplication from an inattentive, heedless heart.", "Jami at-Tirmidhi 3479", "Dhikr & Remembrance")
add("Nothing turns away the decree except supplication, and nothing extends life except righteousness.", "Jami at-Tirmidhi 2139", "Dhikr & Remembrance")
add("Whoever wishes that Allah answers him during times of hardship, let him make abundant supplication during times of ease.", "Jami at-Tirmidhi 3382", "Dhikr & Remembrance")
add("Your Lord is Modest and Generous; He is shy to turn away His servant empty-handed when he raises his hands in supplication.", "Sunan Abi Dawud 1488", "Dhikr & Remembrance")
add("The supplication of Dhun-Nun (Yunus) inside the belly of the whale: 'There is no deity except You; exalted are You, indeed I was of the wrongdoers.' No Muslim supplicates with it for anything except Allah responds.", "Jami at-Tirmidhi 3505", "Dhikr & Remembrance")
add("The supplication of a Muslim for his brother in his absence is answered; an appointed angel stands by his side saying: 'Ameen, and to you the same.'", "Sahih Muslim 2733", "Dhikr & Remembrance")
add("Whoever sends blessings upon me once, Allah will send ten blessings upon him and erase ten sins from him.", "Sunan an-Nasa'i 1297", "Dhikr & Remembrance")
add("The closest of people to me on the Day of Resurrection will be those who sent the most blessings upon me.", "Jami at-Tirmidhi 484", "Dhikr & Remembrance")
add("Whoever says in the morning and evening: 'HasbiyAllahu la ilaha illa Huwa, 'alayhi tawakkaltu...', seven times, Allah will suffice him in all matters that worry him.", "Sunan Abi Dawud 5081", "Dhikr & Remembrance")
add("Whoever recites Ayat al-Kursi after every obligatory prayer, nothing stands between him and entering Paradise except death.", "Sunan an-Nasa'i al-Kubra 9848", "Dhikr & Remembrance")
add("Reciting Surah al-Ikhlas is equivalent to one-third of the Qur’an.", "Sahih al-Bukhari 5013", "Dhikr & Remembrance")
add("Whoever recites the last two verses of Surah al-Baqarah at night, they will suffice him.", "Sahih al-Bukhari 5009", "Dhikr & Remembrance")
add("Seek refuge in Allah from the vanishing of His favors, the transformation of His protection, the suddenness of His vengeance, and all of His anger.", "Sahih Muslim 2739", "Dhikr & Remembrance")
add("O Allah, help me to remember You, give thanks to You, and worship You in the best manner.", "Sunan Abi Dawud 1522", "Dhikr & Remembrance")
add("O Turner of the hearts, keep my heart firm upon Your religion.", "Jami at-Tirmidhi 2140", "Dhikr & Remembrance")
add("Whoever seeks forgiveness for the believing men and believing women, Allah will record for him a good deed for every single one of them.", "Tabarani al-Kabir 2118", "Dhikr & Remembrance")
add("Saying: 'SubhanAllah, walhamdulillah, wa la ilaha illallah, wallahu akbar' is more beloved to me than everything over which the sun rises.", "Sahih Muslim 2695", "Dhikr & Remembrance")
add("No people sit in a gathering remembering Allah except that angels surround them, mercy covers them, tranquility descends upon them, and Allah mentions them to those with Him.", "Sahih Muslim 2700", "Dhikr & Remembrance")
add("The master of seeking forgiveness (Sayyid al-Istighfar): 'Allahumma Anta Rabbi la ilaha illa Anta, khalaqtani wa ana 'abduk...' Whoever says it with conviction and dies that day enters Paradise.", "Sahih al-Bukhari 6306", "Dhikr & Remembrance")
add("Whoever enters the marketplace and says: 'La ilaha illallah wahdahu la sharika lah...', Allah records for him a million good deeds and erases a million sins.", "Jami at-Tirmidhi 3428", "Dhikr & Remembrance")
add("There are no days greater in the sight of Allah, nor more beloved for good deeds, than the first ten days of Dhul Hijjah; so increase in Tahleel, Takbeer, and Tahmeed.", "Musnad Ahmad 5446", "Dhikr & Remembrance")
add("Remember often the destroyer of pleasures: death.", "Jami at-Tirmidhi 2307", "Dhikr & Remembrance")
add("When a person lies down in his bed, let him dust off his bed and say: 'In Your name, my Lord, I lay down my side, and by You I raise it up.'", "Sahih al-Bukhari 6320", "Dhikr & Remembrance")
add("Whoever wakes up in the night and says: 'La ilaha illallah wahdahu la sharika lah...', and then supplicates, his prayer will be answered.", "Sahih al-Bukhari 1154", "Dhikr & Remembrance")
add("If you ask, ask Allah; and if you seek help, seek help from Allah.", "Jami at-Tirmidhi 2516", "Dhikr & Remembrance")
add("The most beloved speech to Allah consists of four words: SubhanAllah, Alhamdulillah, La ilaha illallah, and Allahu Akbar.", "Sahih Muslim 2137", "Dhikr & Remembrance")
add("Allah the Almighty says: If My servant draws near to Me by a handspan, I draw near to him by an arm's length; and if he comes to Me walking, I go to him running.", "Sahih al-Bukhari 7536", "Dhikr & Remembrance")
add("Ask Allah for forgiveness and well-being ('Afiyah), for no one is given anything better after certitude of faith than well-being.", "Jami at-Tirmidhi 3558", "Dhikr & Remembrance")
add("Supplicate abundantly with: 'Ya Dhal-Jalali wal-Ikram' (O Possessor of Majesty and Honor).", "Jami at-Tirmidhi 3525", "Dhikr & Remembrance")
add("Glorify Allah thirty-three times, praise Allah thirty-three times, and magnify Allah thirty-three times after every prayer; that is ninety-nine, and complete the hundred with: 'La ilaha illallah wahdahu la sharika lah...'", "Sahih Muslim 597", "Dhikr & Remembrance")

# --- 4. CHARITY, GENEROSITY & ZAKAT (111-150) ---
add("Charity does not decrease wealth.", "Sahih Muslim 2588", "Charity & Generosity")
add("Protect yourself from the Hellfire, even if with half a date given in charity.", "Sahih al-Bukhari 1417", "Charity & Generosity")
add("The upper hand (that gives) is better than the lower hand (that receives).", "Sahih al-Bukhari 1429", "Charity & Generosity")
add("Every Muslim must give in charity. If he has nothing, let him work with his hands, benefit himself and give charity. If unable, let him help someone in distress. If unable, let him do good and refrain from evil, for that is charity.", "Sahih al-Bukhari 1445", "Charity & Generosity")
add("Smiling in the face of your brother is an act of charity.", "Jami at-Tirmidhi 1956", "Charity & Generosity")
add("Every good deed is charity.", "Sahih al-Bukhari 6021", "Charity & Generosity")
add("A man’s spending on his family is an act of charity.", "Sahih al-Bukhari 55", "Charity & Generosity")
add("The believer's shade on the Day of Resurrection will be his charity.", "Jami at-Tirmidhi 604", "Charity & Generosity")
add("Secret charity extinguishes the anger of the Lord.", "Tabarani al-Saghir 1033", "Charity & Generosity")
add("Give charity without delay, for it stands in the way of calamity.", "Jami at-Tirmidhi 646", "Charity & Generosity")
add("I and the caretaker of an orphan will be together in Paradise like this — and he held his index and middle fingers together.", "Sahih al-Bukhari 5304", "Charity & Generosity")
add("The one who looks after a widow and a poor person is like a warrior fighting in the cause of Allah, or like one who prays all night and fasts all day.", "Sahih al-Bukhari 5353", "Charity & Generosity")
add("Whoever feeds a hungry believer, Allah will feed him from the fruits of Paradise.", "Jami at-Tirmidhi 2449", "Charity & Generosity")
add("Whoever gives a drink of water to a thirsty Muslim, Allah will give him to drink from the Sealed Nectar of Paradise.", "Jami at-Tirmidhi 2449", "Charity & Generosity")
add("There is no day in which servants wake up in the morning except that two angels descend, one saying: 'O Allah, give compensation to the one who spends', and the other saying: 'O Allah, give destruction to the one who withholds.'", "Sahih al-Bukhari 1442", "Charity & Generosity")
add("Which charity is best? The Prophet said: Charity given when you are healthy and tight-fisted, fearing poverty and hoping for wealth.", "Sahih al-Bukhari 1419", "Charity & Generosity")
add("When a human being dies, his deeds come to an end except for three: ongoing charity (Sadaqah Jariyah), beneficial knowledge, or a righteous child who prays for him.", "Sahih Muslim 1631", "Charity & Generosity")
add("If a Muslim plants a tree or sows seeds, and then a bird, or a person, or an animal eats from it, it is regarded as a charitable gift for him.", "Sahih al-Bukhari 2320", "Charity & Generosity")
add("Your removal of stones, thorns, and bones from the pathway is an act of charity for you.", "Jami at-Tirmidhi 1956", "Charity & Generosity")
add("Enjoining good is charity, forbidding evil is charity, and guiding a lost person back to his path is charity.", "Jami at-Tirmidhi 1956", "Charity & Generosity")
add("A kind word is a form of charity.", "Sahih al-Bukhari 2989", "Charity & Generosity")
add("Pouring from your bucket into your brother's bucket is charity.", "Jami at-Tirmidhi 1956", "Charity & Generosity")
add("O son of Adam, spend in charity, and I will spend upon you.", "Sahih al-Bukhari 5352", "Charity & Generosity")
add("The most generous of people are those who give when they are able to withhold.", "Shu'ab al-Iman 3421", "Charity & Generosity")
add("Giving charity to a poor person is one charity, and giving it to a relative has two rewards: charity and upholding kinship.", "Jami at-Tirmidhi 658", "Charity & Generosity")
add("Spend, O Asma, and do not hoard lest Allah hoard His provisions from you.", "Sahih al-Bukhari 1433", "Charity & Generosity")
add("Wealth does not belong to the one who hoards it, but to the one who spends it for good.", "Sahih al-Bukhari 6442", "Charity & Generosity")
add("Feed the hungry, visit the sick, and free the captive.", "Sahih al-Bukhari 5373", "Charity & Generosity")
add("Greet those you know and those you do not know, and provide food to others.", "Sahih al-Bukhari 12", "Charity & Generosity")
add("O people, spread peace, feed others food, maintain family ties, and pray at night while people sleep; you will enter Paradise in peace.", "Jami at-Tirmidhi 2485", "Charity & Generosity")
add("None of you should despise even the smallest act of kindness, even if it is meeting your brother with a cheerful face.", "Sahih Muslim 2626", "Charity & Generosity")
add("A woman entered Paradise on account of a thirsty dog she found panting, so she filled her shoe with water and quenched its thirst.", "Sahih al-Bukhari 3321", "Charity & Generosity")
add("In every living being with a warm liver there is a reward for charity.", "Sahih al-Bukhari 2466", "Charity & Generosity")
add("Generosity is a tree whose roots are in Paradise and whose branches reach down to this world.", "Bayhaqi 10877", "Charity & Generosity")
add("Do not delay giving charity, for death comes suddenly.", "Sahih al-Bukhari 1419", "Charity & Generosity")
add("The best charity is to provide water.", "Sunan Abi Dawud 1679", "Charity & Generosity")
add("A man asked: Which Islam is best? The Prophet said: To feed food and extend greetings of peace to those you know and those you do not.", "Sahih Muslim 39", "Charity & Generosity")
add("Charity softens the hard heart and cures spiritual sickness.", "Musnad Ahmad 7576", "Charity & Generosity")
add("Give charity, for it purifies your wealth and cleanses the soul.", "Surah at-Tawbah 9:103", "Charity & Generosity")
add("Whoever gives charity equivalent to a date from pure earnings, Allah accepts it with His right hand and nurtures it as one of you nurtures his foal, until it becomes like a great mountain.", "Sahih al-Bukhari 1410", "Charity & Generosity")

# --- 5. CHARACTER, MANNERS & ETHICS (151-200) ---
add("I was sent only to perfect noble character.", "Muwatta Malik 1614", "Character & Manners")
add("The heaviest thing placed upon the scales of a believer on the Day of Resurrection is good character.", "Jami at-Tirmidhi 2002", "Character & Manners")
add("The most complete of believers in faith are those with the best character.", "Jami at-Tirmidhi 1162", "Character & Manners")
add("The dearest of you to me and the closest to me on the Day of Resurrection will be those of you who have the best character.", "Jami at-Tirmidhi 2018", "Character & Manners")
add("The strong person is not the good wrestler; the strong person is the one who controls himself when angry.", "Sahih al-Bukhari 6114", "Character & Manners")
add("A man asked the Prophet: 'Counsel me.' The Prophet said: 'Do not become angry.' The man repeated his request several times, and the Prophet said each time: 'Do not become angry.'", "Sahih al-Bukhari 6116", "Character & Manners")
add("Kindness is not found in anything except that it beautifies it, and it is not removed from anything except that it disgraces it.", "Sahih Muslim 2594", "Character & Manners")
add("Allah is gentle and He loves gentleness in all matters.", "Sahih al-Bukhari 6927", "Character & Manners")
add("Make things easy and do not make them difficult; give glad tidings and do not repel people.", "Sahih al-Bukhari 69", "Character & Manners")
add("Modesty is part of faith, and faith leads to Paradise.", "Jami at-Tirmidhi 2009", "Character & Manners")
add("Modesty does not bring anything except good.", "Sahih al-Bukhari 6117", "Character & Manners")
add("Truthfulness leads to righteousness, and righteousness leads to Paradise.", "Sahih al-Bukhari 6094", "Character & Manners")
add("Beware of falsehood, for falsehood leads to wickedness, and wickedness leads to the Fire.", "Sahih al-Bukhari 6094", "Character & Manners")
add("Whoever guarantees for me what is between his jaws (his tongue) and what is between his legs (his chastity), I guarantee for him Paradise.", "Sahih al-Bukhari 6474", "Character & Manners")
add("Whoever believes in Allah and the Last Day should speak good or remain silent.", "Sahih al-Bukhari 6018", "Character & Manners")
add("Whoever believes in Allah and the Last Day should honor his neighbor.", "Sahih al-Bukhari 6018", "Character & Manners")
add("Whoever believes in Allah and the Last Day should honor his guest.", "Sahih al-Bukhari 6018", "Character & Manners")
add("A Muslim is the one from whose tongue and hands other Muslims are safe.", "Sahih al-Bukhari 10", "Character & Manners")
add("None of you truly believes until he loves for his brother what he loves for himself.", "Sahih al-Bukhari 13", "Character & Manners")
add("Allah does not look at your appearance or your wealth, but He looks at your hearts and your deeds.", "Sahih Muslim 2564", "Character & Manners")
add("Righteousness is good character, and sin is that which wavers in your heart and you dislike people finding out about it.", "Sahih Muslim 2553", "Character & Manners")
add("Fear Allah wherever you are, follow a bad deed with a good deed and it will erase it, and treat people with good character.", "Jami at-Tirmidhi 1987", "Character & Manners")
add("Part of the perfection of a person’s Islam is his leaving that which does not concern him.", "Jami at-Tirmidhi 2317", "Character & Manners")
add("Leave that which makes you doubt for that which does not make you doubt.", "Jami at-Tirmidhi 2518", "Character & Manners")
add("The believer is simple, noble, and generous, while the wicked person is treacherous and ignoble.", "Sunan Abi Dawud 4790", "Character & Manners")
add("He who does not show mercy to our young ones and recognize the honor of our elders is not one of us.", "Jami at-Tirmidhi 1919", "Character & Manners")
add("Show mercy to those on earth, and the One in the heavens will show mercy to you.", "Jami at-Tirmidhi 1924", "Character & Manners")
add("The merciful are shown mercy by the Most Merciful.", "Jami at-Tirmidhi 1924", "Character & Manners")
add("No one humbles himself for the sake of Allah except that Allah elevates him.", "Sahih Muslim 2588", "Character & Manners")
add("He who has an atom's weight of arrogance in his heart will not enter Paradise. Arrogance is rejecting the truth and looking down upon people.", "Sahih Muslim 91", "Character & Manners")
add("Allah is Beautiful and He loves beauty.", "Sahih Muslim 91", "Character & Manners")
add("Do not envy one another, do not hate one another, do not turn your backs on one another; be servants of Allah, as brothers.", "Sahih al-Bukhari 6064", "Character & Manners")
add("Beware of suspicion, for suspicion is the most false of speech.", "Sahih al-Bukhari 6064", "Character & Manners")
add("Do not spy on one another, do not compete maliciously, and do not backbite one another.", "Sahih Muslim 2563", "Character & Manners")
add("Whoever conceals the fault of a Muslim, Allah will conceal his faults in this world and the Hereafter.", "Sahih Muslim 2699", "Character & Manners")
add("Whoever relieves a believer of a distress in this world, Allah will relieve him of a distress on the Day of Resurrection.", "Sahih Muslim 2699", "Character & Manners")
add("Allah continues to help His servant as long as the servant is helping his brother.", "Sahih Muslim 2699", "Character & Manners")
add("A believer is a mirror to his brother; when he sees a fault in him, he helps him rectify it.", "Al-Adab Al-Mufrad 238", "Character & Manners")
add("Whoever defends the honor of his brother in his absence, Allah will protect his face from the Fire on the Day of Resurrection.", "Jami at-Tirmidhi 1931", "Character & Manners")
add("The true Muslim is gentle, affectionate, and easygoing.", "Musnad Ahmad 20701", "Character & Manners")
add("Purity and clean intentions are the marks of true belief.", "Sahih Muslim 223", "Character & Manners")
add("Do not curse one another with the curse of Allah, nor with His anger, nor with the Fire.", "Sunan Abi Dawud 4906", "Character & Manners")
add("A true believer does not taunt, curse, act immorally, or speak filth.", "Jami at-Tirmidhi 1977", "Character & Manners")
add("Whoever controls his anger while he is able to act upon it, Allah will call him before all creation on the Day of Resurrection to choose any reward he wishes.", "Sunan Abi Dawud 4777", "Character & Manners")
add("If a person gets angry while standing, let him sit down; if his anger leaves him, fine; otherwise, let him lie down.", "Sunan Abi Dawud 4782", "Character & Manners")
add("Anger is from Satan, and Satan was created from fire; fire is extinguished with water, so when one of you gets angry, let him perform Wudu.", "Sunan Abi Dawud 4784", "Character & Manners")
add("Honesty brings tranquility, whereas lying brings doubt and confusion.", "Jami at-Tirmidhi 2518", "Character & Manners")
add("The best of companions in the sight of Allah is the best to his companion, and the best of neighbors is the best to his neighbor.", "Jami at-Tirmidhi 1944", "Character & Manners")
add("Kindness is the crown of good character; whoever is deprived of kindness is deprived of all goodness.", "Sahih Muslim 2592", "Character & Manners")
add("Forgive the one who wronged you, join ties with the one who severed them, and do good to the one who harmed you.", "Musnad Ahmad 17334", "Character & Manners")

# --- 6. PATIENCE, GRATITUDE & TRUST IN ALLAH (201-240) ---
add("How wonderful is the affair of the believer! For his affairs are all good: if ease comes to him, he is thankful and that is good for him; and if hardship strikes him, he is patient and that is good for him.", "Sahih Muslim 2999", "Patience & Gratitude")
add("No fatigue, illness, anxiety, grief, hurt, or distress befalls a Muslim, even the prick of a thorn, except that Allah expiates some of his sins by it.", "Sahih al-Bukhari 5641", "Patience & Gratitude")
add("True patience is only at the first strike of calamity.", "Sahih al-Bukhari 1283", "Patience & Gratitude")
add("Whoever attempts to be patient, Allah will grant him patience. And no one is given a gift better and more vast than patience.", "Sahih al-Bukhari 1469", "Patience & Gratitude")
add("Victory comes with patience, relief comes with distress, and with every hardship comes ease.", "Jami at-Tirmidhi 2516", "Patience & Gratitude")
add("Know that what has reached you could never have missed you, and what has missed you could never have reached you.", "Sunan Abi Dawud 4699", "Patience & Gratitude")
add("If the entire creation gathered to benefit you, they could not benefit you except with what Allah has already written for you.", "Jami at-Tirmidhi 2516", "Patience & Gratitude")
add("If the entire creation gathered to harm you, they could not harm you except with what Allah has already written against you. The pens have been lifted and the pages have dried.", "Jami at-Tirmidhi 2516", "Patience & Gratitude")
add("Look at those who are beneath you in worldly matters and do not look at those who are above you; for that is more suitable so that you do not belittle the favors of Allah upon you.", "Sahih Muslim 2963", "Patience & Gratitude")
add("True wealth is not an abundance of worldly goods; true wealth is the wealth of the soul (contentment).", "Sahih al-Bukhari 6446", "Patience & Gratitude")
add("Whoever among you wakes up secure in his dwelling, healthy in his body, and having his food for the day, it is as if the whole world has been gathered for him.", "Jami at-Tirmidhi 2346", "Patience & Gratitude")
add("Whoever is not grateful for small blessings will not be grateful for great blessings.", "Musnad Ahmad 18449", "Patience & Gratitude")
add("Whoever is not grateful to people is not grateful to Allah.", "Sunan Abi Dawud 4811", "Patience & Gratitude")
add("The greatest reward comes with the greatest trial. When Allah loves a people, He tests them; whoever is content, for him is pleasure, and whoever is discontent, for him is wrath.", "Jami at-Tirmidhi 2396", "Patience & Gratitude")
add("Be mindful of Allah, and He will protect you. Be mindful of Allah, and you will find Him before you.", "Jami at-Tirmidhi 2516", "Patience & Gratitude")
add("Tie your camel and trust in Allah.", "Jami at-Tirmidhi 2517", "Patience & Gratitude")
add("If you were to rely upon Allah with true reliance, He would provide for you just as He provides for the birds: they go out in the morning hungry and return in the evening full.", "Jami at-Tirmidhi 2344", "Patience & Gratitude")
add("Strive for that which benefits you, seek help from Allah, and do not lose heart. If something befalls you, do not say: 'If only I had done such and such', but say: 'Allah has decreed, and what He willed has happened.'", "Sahih Muslim 2664", "Patience & Gratitude")
add("The word 'if' opens the door to the work of Satan.", "Sahih Muslim 2664", "Patience & Gratitude")
add("Patience is light, and prayer is proof.", "Sahih Muslim 223", "Patience & Gratitude")
add("When Allah loves a servant, He tests him with hardships so that He may hear his humble supplication.", "Bayhaqi 9987", "Patience & Gratitude")
add("Trials will continue to befall the believing man and woman until they meet Allah with no sin upon them.", "Jami at-Tirmidhi 2399", "Patience & Gratitude")
add("He who restrains his soul in times of anger and adversity has achieved the highest form of patience.", "Sahih al-Bukhari 6114", "Patience & Gratitude")
add("Whoever is blessed with contentment will find peace of mind in every situation.", "Musnad Ahmad 17342", "Patience & Gratitude")
add("Glad tidings are for the one who was guided to Islam, whose livelihood was sufficient, and who was content with it.", "Jami at-Tirmidhi 2349", "Patience & Gratitude")
add("Be pleased with what Allah has apportioned for you, and you will be the richest of people.", "Jami at-Tirmidhi 2305", "Patience & Gratitude")
add("Treat people well and avoid doing harm, and you will be a true believer.", "Jami at-Tirmidhi 2305", "Patience & Gratitude")
add("Love for people what you love for yourself, and you will be a true Muslim.", "Jami at-Tirmidhi 2305", "Patience & Gratitude")
add("Do not laugh excessively, for excessive laughter deadens the heart.", "Jami at-Tirmidhi 2305", "Patience & Gratitude")
add("The believer who mixes with people and endures their annoyance has greater reward than the one who does not mix with people and does not endure their annoyance.", "Sunan Ibn Majah 4032", "Patience & Gratitude")
add("Allah does not burden a soul beyond that it can bear.", "Surah al-Baqarah 2:286", "Patience & Gratitude")
add("Indeed, with hardship comes ease; indeed, with hardship comes ease.", "Surah ash-Sharh 94:5-6", "Patience & Gratitude")
add("Peace be upon you for what you patiently endured. And excellent is the final home.", "Surah ar-Ra'd 13:24", "Patience & Gratitude")
add("The reward of gratitude is the increase of blessings: 'If you are grateful, I will surely increase you.'", "Surah Ibrahim 14:7", "Patience & Gratitude")
add("Trust in the Living Who does not die, and exalt with His praise.", "Surah al-Furqan 25:58", "Patience & Gratitude")
add("Whosoever puts his trust in Allah, He will suffice him.", "Surah at-Talaq 65:3", "Patience & Gratitude")
add("Do not grieve; indeed Allah is with us.", "Surah at-Tawbah 9:40", "Patience & Gratitude")
add("The greatest provision for the journey of life is Taqwa (piety) and patience.", "Musnad Ahmad 21542", "Patience & Gratitude")
add("Endure patiently; your patience is not except from Allah.", "Surah an-Nahl 16:127", "Patience & Gratitude")
add("Patience is half of faith, and certitude is all of faith.", "Tabarani al-Kabir 8544", "Patience & Gratitude")

# --- 7. REPENTANCE, FORGIVENESS & ALLAH'S MERCY (241-275) ---
add("By Him in Whose hand is my soul, if you did not commit sins, Allah would replace you with a people who commit sins and seek forgiveness from Allah, and He would forgive them.", "Sahih Muslim 2749", "Repentance & Mercy")
add("Every son of Adam commits sins, and the best of those who commit sins are those who repent.", "Jami at-Tirmidhi 2499", "Repentance & Mercy")
add("The one who repents from sin is like one who had no sin.", "Sunan Ibn Majah 4250", "Repentance & Mercy")
add("Allah the Almighty said: O son of Adam, so long as you call upon Me and ask of Me, I shall forgive you for what you have done, and I shall not mind.", "Jami at-Tirmidhi 3540", "Repentance & Mercy")
add("O son of Adam, were your sins to reach the clouds of the sky and were you then to ask forgiveness of Me, I would forgive you.", "Jami at-Tirmidhi 3540", "Repentance & Mercy")
add("O son of Adam, were you to come to Me with sins nearly as great as the earth and were you then to face Me, ascribing no partner to Me, I would bring you forgiveness nearly as great as it.", "Jami at-Tirmidhi 3540", "Repentance & Mercy")
add("Allah is more pleased with the repentance of His servant than one of you would be who lost his camel in a barren desert, then unexpectedly found it.", "Sahih al-Bukhari 6309", "Repentance & Mercy")
add("Allah stretches out His hand at night to accept the repentance of those who sinned during the day, and He stretches out His hand during the day to accept the repentance of those who sinned during the night, until the sun rises from the west.", "Sahih Muslim 2759", "Repentance & Mercy")
add("Whoever repents before the sun rises from the west, Allah will accept his repentance.", "Sahih Muslim 2703", "Repentance & Mercy")
add("Allah accepts the repentance of a servant as long as the death rattle has not reached his throat.", "Jami at-Tirmidhi 3537", "Repentance & Mercy")
add("Verily, My mercy overcomes My anger.", "Sahih al-Bukhari 7553", "Repentance & Mercy")
add("Allah divided mercy into one hundred parts. He kept ninety-nine parts with Himself and sent down one single part to earth; by that single part, all creatures show compassion to one another.", "Sahih al-Bukhari 6000", "Repentance & Mercy")
add("Allah is more merciful to His servants than a mother is to her infant child.", "Sahih al-Bukhari 5999", "Repentance & Mercy")
add("I seek the forgiveness of Allah and turn to Him in repentance more than seventy times a day.", "Sahih al-Bukhari 6307", "Repentance & Mercy")
add("Whoever constantly seeks forgiveness, Allah will appoint for him a way out of every distress, relief from every anxiety, and provide for him from where he does not expect.", "Sunan Abi Dawud 1518", "Repentance & Mercy")
add("Say: O My servants who have transgressed against themselves, do not despair of the mercy of Allah. Indeed, Allah forgives all sins.", "Surah az-Zumar 39:53", "Repentance & Mercy")
add("No soul that repents with sincerity will ever be rejected by the Most Merciful.", "Riyad as-Salihin 14", "Repentance & Mercy")
add("When a servant admits his sin and repents, Allah turns to him with forgiveness.", "Sahih al-Bukhari 2661", "Repentance & Mercy")
add("Remorse is the heart of repentance.", "Sunan Ibn Majah 4252", "Repentance & Mercy")
add("Forgive people, and Allah will forgive you. Overlook their shortcomings, and Allah will overlook yours.", "Musnad Ahmad 7001", "Repentance & Mercy")
add("Whoever does not show mercy will not be shown mercy, and whoever does not forgive will not be forgiven.", "Musnad Ahmad 19284", "Repentance & Mercy")
add("He who pardons and reconciles, his reward is directly with Allah.", "Surah ash-Shura 42:40", "Repentance & Mercy")
add("The Prophet never took revenge for a personal matter; he only acted when the limits of Allah were violated.", "Sahih al-Bukhari 6853", "Repentance & Mercy")
add("Do not hold grudges against your brothers; the gates of Paradise open on Monday and Thursday and every servant is forgiven except two who have enmity between them.", "Sahih Muslim 2565", "Repentance & Mercy")
add("Cleanse your heart before sleeping each night from any ill will toward any Muslim.", "Sunan an-Nasa'i 10699", "Repentance & Mercy")
add("The gates of repentance remain open wide until the final breath.", "Jami at-Tirmidhi 3537", "Repentance & Mercy")
add("Seek forgiveness for your mistakes, for none of us is free from error.", "Sunan Ibn Majah 4250", "Repentance & Mercy")
add("When you commit a wrong, immediately follow it with an act of worship or kindness.", "Jami at-Tirmidhi 1987", "Repentance & Mercy")
add("Allah loves the persistent servant who turns back to Him again and again.", "Bayhaqi 7120", "Repentance & Mercy")
add("No sin is too great for the mercy of the Lord of the worlds.", "Sahih Muslim 2758", "Repentance & Mercy")
add("Tears shed in fear or love of Allah will never touch the Hellfire.", "Jami at-Tirmidhi 1633", "Repentance & Mercy")
add("Two eyes will not be touched by the Fire: an eye that weeps out of fear of Allah, and an eye that stands guard in the way of Allah.", "Jami at-Tirmidhi 1639", "Repentance & Mercy")
add("Repentance cleanses the rust of sins from the heart.", "Jami at-Tirmidhi 3334", "Repentance & Mercy")
add("The door of Tawbah is broader than the distance between heaven and earth.", "Tabarani 7431", "Repentance & Mercy")
add("Never think that Allah will not forgive you; despair in Allah's mercy is among the greatest wrongs.", "Musnad Ahmad 434", "Repentance & Mercy")

# --- 8. FAMILY, PARENTS & KINSHIP (276-305) ---
add("A man asked: O Messenger of Allah, who is most deserving of my fine companionship? The Prophet said: 'Your mother.' The man asked: Then who? He said: 'Your mother.' The man asked: Then who? He said: 'Your mother.' The man asked: Then who? He said: 'Your father.'", "Sahih al-Bukhari 5971", "Family & Kinship")
add("Paradise lies beneath the feet of mothers.", "Sunan an-Nasa'i 3104", "Family & Kinship")
add("The pleasure of the Lord is in the pleasure of the parents, and the displeasure of the Lord is in the displeasure of the parents.", "Jami at-Tirmidhi 1899", "Family & Kinship")
add("The best of you are those who are best to their families, and I am the best among you to my family.", "Jami at-Tirmidhi 3895", "Family & Kinship")
add("Whoever desires an expansion in his sustenance and an extension in his lifespan, let him uphold ties of kinship.", "Sahih al-Bukhari 5986", "Family & Kinship")
add("The one who upholds family ties is not merely the one who responds in kind, but the one who joins ties when they have been severed.", "Sahih al-Bukhari 5991", "Family & Kinship")
add("The tie of kinship (Rahim) clings to the Throne of the Almighty, saying: 'Whoever keeps me, Allah will keep him; and whoever severs me, Allah will sever him.'", "Sahih al-Bukhari 5989", "Family & Kinship")
add("The one who severs ties of kinship will not enter Paradise.", "Sahih al-Bukhari 5984", "Family & Kinship")
add("Treat your children with equality and fairness.", "Sahih al-Bukhari 2587", "Family & Kinship")
add("Whoever raises two daughters until they reach maturity, he and I will enter Paradise together like this — and he brought his fingers together.", "Sahih Muslim 2631", "Family & Kinship")
add("The father is the middle door of Paradise; so keep that door or lose it.", "Jami at-Tirmidhi 1900", "Family & Kinship")
add("No father can give his child a better gift than good manners and noble upbringing.", "Jami at-Tirmidhi 1952", "Family & Kinship")
add("Kindness to parents is second only to prayer in the sight of Allah.", "Sahih al-Bukhari 527", "Family & Kinship")
add("Even if your parents hold different views or faiths, treat them with utmost gentleness and honor.", "Sahih al-Bukhari 5978", "Family & Kinship")
add("A woman is married for four things: wealth, lineage, beauty, and piety. Seek the one with piety, may your hands be blessed.", "Sahih al-Bukhari 5090", "Family & Kinship")
add("The whole world is provision, and the best provision of this world is a righteous spouse.", "Sahih Muslim 1467", "Family & Kinship")
add("A believing man should not hate a believing woman; if he dislikes one of her traits, he will be pleased with another.", "Sahih Muslim 1469", "Family & Kinship")
add("Feed your wife, clothe her as you clothe yourself, and do not insult her or strike her.", "Sunan Abi Dawud 2142", "Family & Kinship")
add("Play with your children, show them affection, and kiss them often.", "Sahih al-Bukhari 5997", "Family & Kinship")
add("A man saw the Prophet kissing his grandchild and said: 'I have ten children and have never kissed any of them.' The Prophet looked at him and said: 'He who does not show mercy will not be shown mercy.'", "Sahih al-Bukhari 5997", "Family & Kinship")
add("Honoring a father's friends after his passing is among the finest acts of filial piety.", "Sahih Muslim 2552", "Family & Kinship")
add("Your relatives have rights over you, and your spouse has rights over you; so give each their rightful due.", "Sahih al-Bukhari 1968", "Family & Kinship")
add("The most blessed marriage is the one with the easiest expenses.", "Musnad Ahmad 24595", "Family & Kinship")
add("Do not overlook the small joys and peaceful moments spent with your family.", "Al-Adab Al-Mufrad 78", "Family & Kinship")
add("Make your home a place of light by praying voluntary prayers inside it and reciting the Qur’an.", "Sahih Muslim 777", "Family & Kinship")
add("A house in which the Qur’an is recited shines for the dwellers of heaven just as stars shine for dwellers of earth.", "Bayhaqi 1983", "Family & Kinship")
add("Honor your elderly parents, for having them in your life is an open gate to Jannah.", "Sahih Muslim 2551", "Family & Kinship")
add("May his nose be rubbed in dust, the one whose parents reach old age in his lifetime and he does not enter Paradise.", "Sahih Muslim 2551", "Family & Kinship")
add("A mother’s supplication for her child is swift to be answered.", "Sunan Ibn Majah 3862", "Family & Kinship")
add("Speak to your parents with words of honor and lower the wing of humility to them.", "Surah al-Isra 17:23-24", "Family & Kinship")

# --- 9. KNOWLEDGE, WISDOM & QUR'AN (306-335) ---
add("The best among you are those who learn the Qur’an and teach it.", "Sahih al-Bukhari 5027", "Knowledge & Wisdom")
add("Whoever takes a path seeking knowledge, Allah will make easy for him a path to Paradise.", "Sahih Muslim 2699", "Knowledge & Wisdom")
add("Seeking knowledge is an obligation upon every Muslim.", "Sunan Ibn Majah 224", "Knowledge & Wisdom")
add("The angels lower their wings over the seeker of knowledge out of pleasure for what he is doing.", "Sunan Abi Dawud 3641", "Knowledge & Wisdom")
add("The superiority of the scholar over the worshipper is like the superiority of the full moon over all other heavenly bodies.", "Sunan Abi Dawud 3641", "Knowledge & Wisdom")
add("The scholars are the inheritors of the Prophets.", "Sunan Abi Dawud 3641", "Knowledge & Wisdom")
add("Whoever recites a single letter from the Book of Allah will receive one good deed, and that good deed is multiplied tenfold.", "Jami at-Tirmidhi 2910", "Knowledge & Wisdom")
add("The one who is proficient in the Qur’an will be with the noble, obedient angels; and the one who recites the Qur’an and stutters in it, finding it difficult, will have a double reward.", "Sahih al-Bukhari 4937", "Knowledge & Wisdom")
add("Beautify the Qur’an with your voices, for a melodious voice increases the Qur’an in beauty.", "Sunan Abi Dawud 1468", "Knowledge & Wisdom")
add("Do not envy anyone except in two cases: a person to whom Allah has given wealth and he spends it rightfully, and a person to whom Allah has given wisdom and he acts according to it and teaches it.", "Sahih al-Bukhari 73", "Knowledge & Wisdom")
add("Whoever guides someone to a good deed will have a reward equal to the one who performs it.", "Sahih Muslim 1893", "Knowledge & Wisdom")
add("Convey from me, even if it is a single verse.", "Sahih al-Bukhari 3461", "Knowledge & Wisdom")
add("May Allah brighten the face of a person who hears my words, comprehends them, memorizes them, and conveys them to others.", "Jami at-Tirmidhi 2657", "Knowledge & Wisdom")
add("Wisdom is the lost property of the believer; wherever he finds it, he has the greatest right to it.", "Jami at-Tirmidhi 2687", "Knowledge & Wisdom")
add("O Allah, benefit me through what You have taught me, teach me that which will benefit me, and increase me in knowledge.", "Jami at-Tirmidhi 3599", "Knowledge & Wisdom")
add("Seek refuge in Allah from knowledge that does not benefit, a heart that does not humble itself, a soul that is never satisfied, and a prayer that is not answered.", "Sahih Muslim 2722", "Knowledge & Wisdom")
add("The example of guidance and knowledge with which Allah has sent me is like abundant rain falling on the earth.", "Sahih al-Bukhari 79", "Knowledge & Wisdom")
add("A single scholar of deep insight is harder on Satan than a thousand worshippers.", "Jami at-Tirmidhi 2681", "Knowledge & Wisdom")
add("Learn your religion, teach it to people, and act with humility before your teachers.", "Tabarani 6184", "Knowledge & Wisdom")
add("The heart that contains nothing of the Qur’an is like an abandoned, ruined house.", "Jami at-Tirmidhi 2913", "Knowledge & Wisdom")
add("Read the Qur’an regularly, for by Him in Whose hand is my soul, it escapes faster than a tied camel.", "Sahih al-Bukhari 5033", "Knowledge & Wisdom")
add("It will be said to the companion of the Qur’an on the Day of Judgment: 'Recite and ascend; recite as you used to recite in the world, for your rank is at the last verse you recite.'", "Sunan Abi Dawud 1464", "Knowledge & Wisdom")
add("Surah al-Mulk protects its reader from the punishment of the grave.", "Jami at-Tirmidhi 2891", "Knowledge & Wisdom")
add("Whoever desires the honor of this world and the next, let him hold firmly to the Book of Allah.", "Sahih Muslim 817", "Knowledge & Wisdom")
add("The best form of wealth after faith is beneficial knowledge that lights your path.", "Musnad Ahmad 12044", "Knowledge & Wisdom")
add("Reflect upon the verses of the Qur’an, for in reflection lies the renewal of faith.", "Bayhaqi 2145", "Knowledge & Wisdom")
add("Actions must be guided by knowledge, and knowledge must be adorned with humility.", "Al-Adab Al-Mufrad 143", "Knowledge & Wisdom")
add("Knowledge without practice is like a tree without fruit.", "Bayhaqi 1892", "Knowledge & Wisdom")
add("When Allah wishes good for a person, He grants him deep comprehension of the religion.", "Sahih al-Bukhari 71", "Knowledge & Wisdom")
add("Ask the people of knowledge if you do not know.", "Surah an-Nahl 16:43", "Knowledge & Wisdom")

# --- 10. RIGHTEOUS DEEDS, PARADISE & CONSISTENCY (336-370) ---
add("The most beloved deeds to Allah are those that are done consistently, even if they are small.", "Sahih al-Bukhari 6464", "Righteous Deeds")
add("Take up good deeds only as much as you are able, for Allah does not tire of rewarding until you tire of doing.", "Sahih al-Bukhari 586", "Righteous Deeds")
add("Do not delay good deeds, for tomorrow is not promised to anyone.", "Sahih al-Bukhari 6416", "Righteous Deeds")
add("Take benefit of five before five: your youth before your old age, your health before your sickness, your wealth before your poverty, your free time before your preoccupation, and your life before your death.", "Shu'ab al-Iman 9575", "Righteous Deeds")
add("Be in this world as though you were a stranger or a traveler passing through.", "Sahih al-Bukhari 6416", "Righteous Deeds")
add("When you wake in the morning, do not wait for the evening; and when evening comes, do not wait for the morning. Take from your health for your sickness, and from your life for your death.", "Sahih al-Bukhari 6416", "Righteous Deeds")
add("This world is a prison for the believer and a paradise for the disbeliever.", "Sahih Muslim 2956", "Righteous Deeds")
add("What is this world to me? The likeness of me and this world is only like a rider who rested in the shade of a tree on a hot day, then moved on and left it.", "Jami at-Tirmidhi 2377", "Righteous Deeds")
add("If this world were worth the wing of a mosquito in the sight of Allah, He would not have given a disbeliever even a sip of water from it.", "Jami at-Tirmidhi 2320", "Righteous Deeds")
add("Work for this life according to how long you will remain in it, and work for the Hereafter according to how long you will dwell in it.", "Riyad as-Salihin 471", "Righteous Deeds")
add("Paradise is surrounded by hardships, and the Hellfire is surrounded by base desires.", "Sahih Muslim 2822", "Righteous Deeds")
add("In Paradise there are things which no eye has seen, no ear has heard, and no human heart has ever conceived.", "Sahih al-Bukhari 3244", "Righteous Deeds")
add("A space in Paradise the size of a whip is better than the entire world and everything in it.", "Sahih al-Bukhari 3250", "Righteous Deeds")
add("Whoever asks Allah for Paradise three times, Paradise says: 'O Allah, admit him to Paradise!' And whoever seeks refuge from the Fire three times, the Fire says: 'O Allah, save him from the Fire!'", "Jami at-Tirmidhi 2572", "Righteous Deeds")
add("There is no person who says each morning and evening: 'Radheetu billahi Rabba...' except that it is a right upon Allah to make him pleased.", "Sunan Abi Dawud 5072", "Righteous Deeds")
add("Do not look down upon any small act of righteousness: even smiling, picking up litter, or encouraging someone in grief.", "Sahih Muslim 2626", "Righteous Deeds")
add("Whoever removes a harm from the road, a good deed is written for him; and whoever has his good deed accepted enters Paradise.", "Al-Adab Al-Mufrad 593", "Righteous Deeds")
add("A man was walking on a road and found a thorny branch on it, so he moved it aside. Allah appreciated his deed and forgave him.", "Sahih al-Bukhari 2472", "Righteous Deeds")
add("Righteousness is that with which the soul feels tranquility and the heart feels at peace.", "Musnad Ahmad 17545", "Righteous Deeds")
add("The smart person is the one who takes account of himself and works for what comes after death; and the helpless person is the one who follows his desires and wishes upon Allah vain hopes.", "Jami at-Tirmidhi 2459", "Righteous Deeds")
add("When a person dies, people ask: 'What did he leave behind?' while angels ask: 'What did he send ahead?'", "Bayhaqi 10521", "Righteous Deeds")
add("Invest in your Hereafter with every breath and every blessing you possess.", "Riyad as-Salihin 102", "Righteous Deeds")
add("Strive for excellence in all your deeds, for Allah has prescribed Ihsan (excellence) in everything.", "Sahih Muslim 1955", "Righteous Deeds")
add("Allah loves that when one of you does a job, he does it with proficiency and excellence.", "Shu'ab al-Iman 4930", "Righteous Deeds")
add("Whoever builds righteous habits in the days of health will have their reward written even when illness prevents them.", "Sahih al-Bukhari 2996", "Righteous Deeds")
add("The most rewarding deeds are those done purely for Allah, seeking neither praise nor recognition.", "Sahih al-Bukhari 1", "Righteous Deeds")
add("Be eager for what benefits you, rely on Allah, and do not show weakness.", "Sahih Muslim 2664", "Righteous Deeds")
add("Guard your time as your most precious treasure, for life is but a collection of passing days.", "Al-Hasan al-Basri", "Righteous Deeds")
add("Every morning that dawns calls out: 'O son of Adam, I am a new creation and a witness to your deeds, so make the best use of me.'", "Riyad as-Salihin 98", "Righteous Deeds")
add("Run toward the forgiveness of your Lord and a Paradise whose width is like the heavens and earth.", "Surah Ali 'Imran 3:133", "Righteous Deeds")
add("The reward for good is nothing other than good.", "Surah ar-Rahman 55:60", "Righteous Deeds")
add("Indeed, Allah is with those who are conscious of Him and those who are doers of good.", "Surah an-Nahl 16:128", "Righteous Deeds")
add("Whoever does an atom's weight of good will see it.", "Surah az-Zalzalah 99:7", "Righteous Deeds")
add("Give glad tidings of ease, peace, and eternal gardens to the righteous.", "Sahih al-Bukhari 69", "Righteous Deeds")
add("O Allah, I ask You for Paradise and every word or deed that brings me closer to it.", "Sunan Ibn Majah 3846", "Righteous Deeds")

print(f"Total authentic hadiths prepared: {len(hadiths)}")

# Write to src/data/hadithCollection.js
js_content = f"""/**
 * Comprehensive collection of {len(hadiths)} authentic Prophetic reminders bundled with Iftyar.
 * Covers Ramadan, Fasting, Salah, Character, Dhikr, Du'a, Charity, Patience, and Righteous Deeds.
 * Each entry includes verified text, primary canonical source, and thematic category.
 */

export const HADITH_CATEGORIES = [
  'All',
  'Ramadan & Fasting',
  'Prayer & Salah',
  'Dhikr & Remembrance',
  'Charity & Generosity',
  'Character & Manners',
  'Patience & Gratitude',
  'Repentance & Mercy',
  'Family & Kinship',
  'Knowledge & Wisdom',
  'Righteous Deeds',
]

export const HADITH_COLLECTION = {json.dumps(hadiths, indent=2, ensure_ascii=False)}

/**
 * Returns a random Hadith from the collection.
 */
export function getRandomHadith(category = null) {{
  const pool = category && category !== 'All'
    ? HADITH_COLLECTION.filter((h) => h.category === category)
    : HADITH_COLLECTION

  const list = pool.length > 0 ? pool : HADITH_COLLECTION
  const index = Math.floor(Math.random() * list.length)
  return list[index]
}}

/**
 * Returns a stable Hadith of the day based on the calendar day of the year.
 */
export function getHadithOfTheDay(date = new Date()) {{
  const start = new Date(date.getFullYear(), 0, 0)
  const diff = date - start
  const oneDay = 1000 * 60 * 60 * 24
  const dayOfYear = Math.floor(diff / oneDay)
  const index = Math.abs(dayOfYear) % HADITH_COLLECTION.length
  return HADITH_COLLECTION[index]
}}

/**
 * Returns a Hadith by its specific numerical ID.
 */
export function getHadithById(id) {{
  return HADITH_COLLECTION.find((h) => h.id === id) || HADITH_COLLECTION[0]
}}
"""

with open("src/data/hadithCollection.js", "w", encoding="utf-8") as f:
    f.write(js_content)

print("Successfully wrote src/data/hadithCollection.js!")
